### ISSUE TITLE
Compatibility issues with PHP 8.4

### ISSUE THREAD

**Issue by Whip** [sendgrid/sendgrid-php#1122]
Please fix the code related to this warning to be compatible with PHP 8.4

```
SendGrid\Mail\Mail::__construct(): Implicitly marking parameter $globalSubstitutions as nullable is deprecated, the explicit nullable type must be used instead in ../vendor/sendgrid/sendgrid/lib/mail/Mail.php on line 98
```

**Comment by AdamDomafoldi** [comment]
Please fix this one as well: ` ERROR: Creation of dynamic property SendGrid\\Mail\\Mail::$attachements is deprecated on line 105`

**Comment by dmnlk** [comment]
https://github.com/sendgrid/sendgrid-php/pull/1119
fixed by this PR

**Comment by AdamDomafoldi** [comment]
**It is still not fixed:**  ERROR: Creation of dynamic property SendGrid\\Mail\\Mail::$attachements is deprecated on line 105

**Comment by BaranKeles** [comment]
The SendGrid library has already addressed this deprecation in older version. Updating to the latest version should resolve this issue along with other PHP 8.4 compatibility fixes. Did you try to update?

**This should update**: composer update sendgrid/sendgrid

**Comment by esetnik** [comment]
This issue can be closed, it's resolved by #1119
